/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RoadToSystem */

#ifndef _Included_com_example_android_jniapi_RoadToSystem
#define _Included_com_example_android_jniapi_RoadToSystem
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_example_android_jniapi_RoadToSystem_linkSystemLib
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

